// react/src/views/Todos.tsx
import React, { Component } from 'react'
import { connect } from 'react-redux'
import { fetchTodos } from '../store/actions'
import { AppDispatch, Todo, RootState } from '../store/types'
import  AddTodo from '../components/AddTodo'
import TodoItem from '../components/TodoItem'
type TodoProps = { dispatch: AppDispatch; todos: Todo[] }

class Todos extends Component<TodoProps> {
  componentDidMount() {
    const { dispatch } = this.props
    dispatch(fetchTodos())
  }

  render() {
    const { todos } = this.props
    return (
      <div>
        
          {todos.map(t => (
            <TodoItem todo={t} key={t.id} />
          ))}
       
        <AddTodo />
      </div>
    )
  }
}

const mapStateToProps = (state: RootState): Pick<TodoProps, 'todos'> => {
  const { todos } = state

  return {
    todos
  }
}

export default connect(mapStateToProps)(Todos)

// vue2/src/views/Todos.vue
<template>
  <div class="todos">
    <h3>Todos</h3>
    <todo-item v-for="todo in todos" :key="todo.id" :todo="todo" />
    <add-todo />
  </div>
</template>

<script lang="ts">
import { Component, Vue } from 'vue-property-decorator';
import { State } from 'vuex-class';
import { Todo } from '../store/types';
import TodoItem from './Todos/TodoItem.vue';
import AddTodo from './Todos/AddTodo.vue';

@Component({
  name: 'home',
  components: { AddTodo, TodoItem },
  beforeRouteEnter: (to, from, next) => {
    next(vm => {
      if (!vm.$store.state.authenticated) {
        vm.$router.replace('login');
      }
    });
  },
})
export default class Todos extends Vue {
  mounted() { this.$store.dispatch('fetchTodos'); }

  @State(state => state.todos) todos!: Todo[]
}
</script>

<style lang="scss" scoped>
</style>
