// react/src/components/TodoItem.tsx
import React, { Component } from 'react'
import { connect } from 'react-redux'

import { deleteTodo } from '../store/actions'
import { AppDispatch, Todo } from '../store/types'

type TodoItemProps = {
  dispatch: AppDispatch
  todo: Todo
}

const handleClick = (
  e: React.MouseEvent<HTMLButtonElement>,
  dispatch: AppDispatch,
  todo: Todo
) => {
  e.preventDefault()
  dispatch(deleteTodo(todo))
}

class TodoItem extends Component<TodoItemProps> {
  render() {
    const { dispatch, todo } = this.props
    return (
      <div className="todo">
        <div>{todo.title}</div>
        <button onClick={e => handleClick(e, dispatch, todo)}>Delete</button>
      </div>
    )
  }
}

export default connect()(TodoItem)

// vue/src/views/Todos/TodoItem.vue
<template>
  <div class="todo">
    {{todo.title}}
    <button @click="deleteTodo">Delete</button>
  </div>
</template>

<script lang="ts">
import { Component, Vue, Prop } from 'vue-property-decorator';
import { Todo } from '@/store/types';

@Component({ name: 'todo-item' })
export default class TodoItem extends Vue {
  @Prop({ required: true, type: Object as () => Todo }) todo!: Todo

  deleteTodo() {
    this.$store.dispatch('deleteTodo', this.todo);
  }
}
</script>

<style lang="scss" scoped>

</style>
