// vue/src/views/Register.vue
<template>
  <form
    class="register"
    @submit.prevent="register"
  >
    <label>
      Name
      <input
        v-model="name"
        type="text"
        required
      />
    </label>
    <label>
      Password
      <input
        v-model="password"
        type="password"
        required
      />
    </label>
    <button type="submit">Register</button>
  </form>
</template>

<script lang="ts" setup>
import { ref } from 'vue';
import { useRouter } from 'vue-router';
import { useStore } from '../store';

const store = useStore();
const router = useRouter();
const name = ref('joe');
const password = ref('password');
const register = async () => {
  await store.register({ name: name.value, password: password.value });
  router.push('/');
};
</script>

<style lang="scss" scoped></style>

// angular/src/app/register/register.component.ts
import { Component, OnInit } from '@angular/core';
import { ActivatedRoute, Router } from '@angular/router';

import { register } from '../store';

@Component({
  selector: 'app-register',
  templateUrl: './register.component.html',
  styleUrls: ['./register.component.scss'],
})
export class RegisterComponent implements OnInit {
  constructor(private route: ActivatedRoute, private router: Router) {}

  name = '';
  password = '';

  ngOnInit(): void {}

  async register(): Promise<void> {
    await register(this.name, this.password);
    this.router.navigate(['/']);
  }
}

<form (submit)="register()">
  <label>
    Name
    <input name="name" type="text" [(ngModel)]="name" placeholder="Your name"/>
  </label>
  <label>
    Password
    <input name="password" type="password" [(ngModel)]="password" placeholder="Your password"/>
  </label>
  <button type="submit">Register</button>
</form>
