// vue/src/views/Login.vue
<template>
  <form class="login" @submit.prevent="login">
    <label>
      Login
      <input type="text" required v-model="name" />
    </label>
    <label>
      Password
      <input type="password" required v-model="password" />
    </label>
    <button type="submit">Login</button>
  </form>
</template>

<script lang="ts">
import { Component, Vue } from 'vue-property-decorator';

@Component({ name: 'Login' })
export default class Login extends Vue {
  name: string = 'nikola'

  password: string = 'password'

  async login() {
    const { name, password } = this;
    await this.$store.dispatch('login', { name, password });
    if (this.$store.state.authenticated) { this.$router.push('/'); }
  }
}
</script>

<style lang="scss" scoped>

</style>

// angular/src/app/login/login.component.ts
import { Component, OnInit } from '@angular/core';
import { ActivatedRoute, Router } from '@angular/router';
import { login, state } from '../store';

@Component({
  selector: 'app-login',
  templateUrl: './login.component.html',
  styleUrls: ['./login.component.scss'],
})
export class LoginComponent implements OnInit {
  constructor(private route: ActivatedRoute, private router: Router) {}

  name = '';
  password = '';

  ngOnInit(): void {}

  async login(): Promise<void> {
    await login(this.name, this.password);
    if (state.authenticated) {
      this.router.navigate(['/']);
    }
  }
}

<form (submit)="login()">
  <label>
    Name
    <input name="name" type="text" [(ngModel)]="name" placeholder="Your name"/>
  </label>
  <label>
    Password
    <input name="password" type="password" [(ngModel)]="password" placeholder="Your password"/>
  </label>
  <button type="submit">Login</button>
</form>
