// vue/src/views/AddTodo.vue
<template>
  <form
    class="add-todo"
    @submit.stop.prevent="addTodo"
  >
    <input
      v-model="newTodo"
      type="text"
      required
      autofocus
      placeholder="New todo"
    />
    <button type="submit">Add</button>
  </form>
</template>

<script lang="ts" setup>
import { ref } from 'vue';

import { useRouter } from 'vue-router';
import { useStore } from '~/src/store';

const store = useStore();
const router = useRouter();
const newTodo = ref('');
const addTodo = async () => {
  await store.createTodo(newTodo.value);
  newTodo.value = '';
  router.push('/');
};
</script>

<style lang="scss" scoped></style>

// react/src/components/AddTodo.tsx
import React, { Component } from 'react'
import { connect } from 'react-redux'

import { createTodo } from 'store/actions'
import { AppDispatch } from 'store/types'

type AddTodoProps = {
  dispatch: AppDispatch
}

type AddTodoState = {
  title: string
}

const submit = async (vm: AddTodo, event: React.FormEvent<HTMLFormElement>) => {
  event.preventDefault()
  const { dispatch } = vm.props
  const { title } = vm.state
  await dispatch(createTodo(title))
  vm.setState({ title: '' })
}

class AddTodo extends Component<AddTodoProps, AddTodoState> {
  constructor(props: AddTodoProps) {
    super(props)
    this.state = { title: '' }
  }

  render() {
    return (
      <form onSubmit={e => submit(this, e)}>
        <label>
          <input
            type="text"
            onChange={e => this.setState({ title: e.currentTarget.value })}
            placeholder="New todo"
            value={this.state.title}
          />
        </label>

        <button type="submit">Create ToDo</button>
      </form>
    )
  }
}

export default connect()(AddTodo)
