// react/src/views/Login.tsx
import React, { Component } from 'react'
import { connect } from 'react-redux'

import { login } from 'store/actions'
import { AppDispatch, RootState } from 'store/types'

type LoginProps = {
  authenticated: boolean
  dispatch: AppDispatch
}

type LoginState = {
  name: string
  password: string
}

const submit = (vm: Login, event: React.FormEvent<HTMLFormElement>) => {
  event.preventDefault()
  const { dispatch } = vm.props
  const { name, password } = vm.state
  dispatch(login({ name, password }))
}

class Login extends Component<LoginProps, LoginState> {
  constructor(props: LoginProps) {
    super(props)
    this.state = { name: '', password: '' }
  }

  render() {
    return (
      <form onSubmit={e => submit(this, e)}>
        <label>
          name
          <input
            type="text"
            onChange={e => this.setState({ name: e.currentTarget.value })}
          />
        </label>
        <label>
          password
          <input
            type="password"
            onChange={e => this.setState({ password: e.currentTarget.value })}
          />
        </label>
        <button type="submit">Login</button>
      </form>
    )
  }
}

const mapStateToProps = (
  state: RootState
): Pick<LoginProps, 'authenticated'> => {
  const { authenticated } = state
  return { authenticated }
}

export default connect(mapStateToProps)(Login)

// vue/src/views/Login.vue
<template>
  <form class="login" @submit.prevent="login">
    <label>
      Login
      <input type="text" required v-model="name" />
    </label>
    <label>
      Password
      <input type="password" required v-model="password" />
    </label>
    <button type="submit">Login</button>
  </form>
</template>

<script lang="ts">
import { Component, Vue } from 'vue-property-decorator';

@Component({ name: 'Login' })
export default class Login extends Vue {
  name: string = 'nikola'

  password: string = 'password'

  async login() {
    const { name, password } = this;
    await this.$store.dispatch('login', { name, password });
    if (this.$store.state.authenticated) { this.$router.push('/'); }
  }
}
</script>

<style lang="scss" scoped>

</style>
